### ISSUE TITLE
Making self-play multi-process...

### ISSUE THREAD

**Issue by Akababa** [Akababa/chess-alpha-zero#5]
@Zeta36 @benediamond

I'm still trying to figure out a way to get [this](https://stackoverflow.com/questions/47896904/inverse-of-processpoolexecutor-in-python) to work so that I can have 4 self play games running at once... Do either of you know how to do this?

**Comment by benediamond** [comment]
This is much hackier, but as self-play games are largely independent, couldn't you just run 4 `self` processes in separate windows...?

**Comment by Akababa** [comment]
I finally got it working, thanks. The thing is that they would all have to share the GPU worker (for batch efficiency). The actual speedup wasn't too much because my GPU unfortunately isn't that fast, but I'm curious to see if you get better results on your machine.
