### ISSUE TITLE
question about reloading model

### ISSUE THREAD

**Issue by gooooloo** [Akababa/chess-alpha-zero#8]
https://github.com/Akababa/Chess-Zero/blob/90a5aad05656131506239388557b9f60d16235a3/src/chess_zero/worker/self_play.py#L55

Please correct me if the question doesn't make sense.
When reloading the model, there may be still $max_process -1 processes in the middle stage of the game, is that right? If yes, then this reloading will cause those games using different models during one game.

**Comment by Akababa** [comment]
I haven't tested that, but I believe the `with ProcessPoolExecutor` block has to join() all the processes before it exits.

**Comment by gooooloo** [comment]
Thanks for answering. Yet my question is the scenario like this:
1. Game1 and Game2 are both on, both connect to the "parent process" which is serving model 1.
2. Then game1 finishes, while game2 just played 10 moves( far away from finishing)
3. since Game1 finished, and the reloading condition happenes to be satisfied, then triggering reload_model. Model2 is loaded. Serving model 2 now.
4. But game2's pipe didn't change. Then game2's 11th movement will be using model2.

**Comment by Akababa** [comment]
Yes you're right, I actually never considered that (I focused on supervised learning for now). @benediamond made a fix of this today, check out his fork :)

**Comment by gooooloo** [comment]
Thanks. I see it.
